In [1]:
import numpy as np

In [2]:
# ============================================================
# CREATE SAMPLE DATASETS
# ============================================================

# Numerical dataset representing ages
ages = np.array([18, 22, 25, 30, 35, 40, 45, 50, np.nan])

# Salary dataset
salary = np.array([25000, 32000, 45000, 50000, 62000, 70000, 80000, 95000])

# Names dataset (strings)
names = np.array(["Rohan", "Ankit", "Priya", "Katherine", "John", "Alex", "Elizabeth"])

# Matrix dataset (2D)
scores = np.array([
    [45, 67, 80],
    [56, 90, 88],
    [34, 50, 60],
    [92, 88, 95]
])

print("Ages:", ages)
# Ages: [18. 22. 25. 30. 35. 40. 45. 50. nan]

print("Salary:", salary)
# Salary: [25000 32000 45000 50000 62000 70000 80000 95000]

print("Names:", names)
# Names: ['Rohan' 'Ankit' 'Priya' 'Katherine' 'John' 'Alex' 'Elizabeth']

print("Scores:\n", scores)
# Scores:
# [[45 67 80]
#  [56 90 88]
#  [34 50 60]
#  [92 88 95]]


Ages: [18. 22. 25. 30. 35. 40. 45. 50. nan]
Salary: [25000 32000 45000 50000 62000 70000 80000 95000]
Names: ['Rohan' 'Ankit' 'Priya' 'Katherine' 'John' 'Alex' 'Elizabeth']
Scores:
 [[45 67 80]
 [56 90 88]
 [34 50 60]
 [92 88 95]]


In [3]:
# ============================================================
# 1. BASIC FILTERING USING CONDITIONS
# ============================================================

# Create a boolean mask where condition is true
# ages > 30

mask = ages > 30

print(mask)

# Output
# [False False False False  True  True  True  True False]

# Use boolean mask to filter array
filtered_ages = ages[mask]

print(filtered_ages)

# Output
# [35. 40. 45. 50.]

[False False False False  True  True  True  True False]
[35. 40. 45. 50.]


In [4]:
# ============================================================
# 2. FILTERING USING MULTIPLE CONDITIONS (AND)
# ============================================================

# Use & operator for AND condition
# Select ages greater than 25 AND less than 45

mask = (ages > 25) & (ages < 45)

print(ages[mask])

# Output
# [30. 35. 40.]

# IMPORTANT:
# Parentheses are required when using & and |

[30. 35. 40.]


In [5]:
# ============================================================
# 3. FILTERING USING OR CONDITION
# ============================================================

# Select ages less than 20 OR greater than 45

mask = (ages < 20) | (ages > 45)

print(ages[mask])

# Output
# [18. 50.]

[18. 50.]


In [6]:
# ============================================================
# 4. FILTERING USING np.logical_and / np.logical_or
# ============================================================

mask = np.logical_and(ages > 25, ages < 45)

print(ages[mask])

# Output
# [30. 35. 40.]

mask = np.logical_or(ages < 20, ages > 45)

print(ages[mask])

# Output
# [18. 50.]

[30. 35. 40.]
[18. 50.]


In [7]:
# ============================================================
# 5. FINDING INDICES THAT MATCH CONDITION
# ============================================================

# np.where(condition)
# Returns indices where condition is True

indices = np.where(ages > 35)

print(indices)

# Output
# (array([5,6,7]),)

print(ages[indices])

# Output
# [40. 45. 50.]

(array([5, 6, 7]),)
[40. 45. 50.]


In [8]:
# ============================================================
# 6. CONDITIONAL TRANSFORMATION USING np.where()
# ============================================================

# Syntax
# np.where(condition, value_if_true, value_if_false)

# Replace NaN ages with 0

ages_clean = np.where(np.isnan(ages), 0, ages)

print(ages_clean)

# Output
# [18. 22. 25. 30. 35. 40. 45. 50.  0.]

# Example 2:
# If salary < 50000 → mark as "Low"
# else → "High"


[18. 22. 25. 30. 35. 40. 45. 50.  0.]


In [11]:
salary_level = np.where(salary < 50000, "Low", "High")
print(salary_level)

['Low' 'Low' 'Low' 'High' 'High' 'High' 'High' 'High']


In [12]:
# ============================================================
# 7. MULTIPLE CONDITIONS USING NESTED np.where
# ============================================================

# Categorize salary

salary_category = np.where(
    salary < 40000, "Low",
    np.where(salary < 70000, "Medium", "High")
)

print(salary_category)

# Output
# ['Low' 'Low' 'Medium' 'Medium' 'Medium' 'High' 'High' 'High']

['Low' 'Low' 'Medium' 'Medium' 'Medium' 'High' 'High' 'High']


In [13]:
# ============================================================
# 8. FILTERING USING np.isin()
# ============================================================

# Check if values exist in a list

target = [25, 35, 50]

mask = np.isin(ages, target)

print(mask)

# Output
# [False False True False True False False True False]

print(ages[mask])

# Output
# [25. 35. 50.]

[False False  True False  True False False  True False]
[25. 35. 50.]


In [14]:
# ============================================================
# 9. FILTERING NaN VALUES
# ============================================================

mask = np.isnan(ages)

print(mask)

# Output
# [False False False False False False False False True]

print(ages[mask])

# Output
# [nan]

# Remove NaN

clean_ages = ages[~np.isnan(ages)]

print(clean_ages)

# Output
# [18. 22. 25. 30. 35. 40. 45. 50.]

[False False False False False False False False  True]
[nan]
[18. 22. 25. 30. 35. 40. 45. 50.]


In [15]:
# ============================================================
# 10. CLIPPING VALUES USING np.clip()
# ============================================================

# Limit values within range

clipped_salary = np.clip(salary, 30000, 80000)

print(clipped_salary)

# Output
# [30000 32000 45000 50000 62000 70000 80000 80000]

# Explanation
# values < 30000 → 30000
# values > 80000 → 80000

[30000 32000 45000 50000 62000 70000 80000 80000]


In [16]:
# ============================================================
# 11. APPLYING USER DEFINED FUNCTION (VECTORIZATION)
# ============================================================

# Function to calculate tax

def tax(x):
    return x * 0.1

# Apply function to array

tax_values = tax(salary)

print(tax_values)

# Output
# [2500. 3200. 4500. 5000. 6200. 7000. 8000. 9500.]


[2500. 3200. 4500. 5000. 6200. 7000. 8000. 9500.]


In [17]:
# ============================================================
# 12. APPLYING CUSTOM FUNCTION USING np.vectorize()
# ============================================================

def bonus(x):
    if x > 60000:
        return x * 1.2
    else:
        return x * 1.05

vectorized_bonus = np.vectorize(bonus)

bonus_salary = vectorized_bonus(salary)

print(bonus_salary)

# Output
# [26250. 33600. 47250. 52500. 74400. 84000. 96000. 114000.]


[ 26250.  33600.  47250.  52500.  74400.  84000.  96000. 114000.]


In [18]:
# ============================================================
# 13. STRING TRANSFORMATION USING np.char MODULE
# ============================================================

# Convert to lowercase

lower = np.char.lower(names)

print(lower)

# Output
# ['rohan' 'ankit' 'priya' 'katherine' 'john' 'alex' 'elizabeth']

# Convert to uppercase

upper = np.char.upper(names)

print(upper)

# Output
# ['ROHAN' 'ANKIT' 'PRIYA' 'KATHERINE' 'JOHN' 'ALEX' 'ELIZABETH']

['rohan' 'ankit' 'priya' 'katherine' 'john' 'alex' 'elizabeth']
['ROHAN' 'ANKIT' 'PRIYA' 'KATHERINE' 'JOHN' 'ALEX' 'ELIZABETH']


In [19]:
# ============================================================
# 14. TRUNCATE STRINGS BASED ON LENGTH
# ============================================================

def shorten(name):
    if len(name) > 5:
        return name[:5] + "..."
    else:
        return name

vectorized_short = np.vectorize(shorten)

short_names = vectorized_short(names)

print(short_names)

# Output
# ['Rohan' 'Ankit' 'Priya' 'Kathe...' 'John' 'Alex' 'Eliza...']


['Rohan' 'Ankit' 'Priya' 'Kathe...' 'John' 'Alex' 'Eliza...']


In [21]:
# ============================================================
# 15. REPLACE VALUES USING np.select()
# ============================================================

conditions = [
    salary < 40000,
    salary < 70000,
    salary >= 70000
]

choices = ["Low", "Medium", "High"]

salary_class = np.select(conditions, choices, default="Unknown") # np.select() automatically uses default=0 if you don’t specify one. Your choices are strings ("Low", "Medium", "High"), but the default value is integer 0, so NumPy cannot combine string dtype and integer dtype into one array. Thus here we need to provide the value of default as some string explicitly

print(salary_class)

# Output
# ['Low' 'Low' 'Medium' 'Medium' 'Medium' 'High' 'High' 'High']

['Low' 'Low' 'Medium' 'Medium' 'Medium' 'High' 'High' 'High']


In [22]:
# ============================================================
# 16. TRANSFORM ARRAY VALUES USING ARITHMETIC OPERATIONS
# ============================================================

# Increase all salaries by 10%

new_salary = salary * 1.10

print(new_salary)

# Output
# [27500. 35200. 49500. 55000. 68200. 77000. 88000. 104500.]

[ 27500.  35200.  49500.  55000.  68200.  77000.  88000. 104500.]


In [23]:
# ============================================================
# 17. APPLY TRANSFORMATION ON SPECIFIC INDICES
# ============================================================

salary_copy = salary.copy()

salary_copy[salary_copy > 70000] *= 1.15

print(salary_copy)

# Output
# [25000 32000 45000 50000 62000 70000 92000 109250]

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### **This error happens because your NumPy array has integer type (int64), but when you multiply by 1.15 (a float) NumPy produces float results, and NumPy does not automatically cast floats back to integers with the "same_kind" rule.**

In [24]:
# ============================================================
# 17. APPLY TRANSFORMATION ON SPECIFIC INDICES
# ============================================================

# salary_copy = salary.copy()
salary_copy = salary.astype(float)
salary_copy[salary_copy > 70000] *= 1.15

print(salary_copy)

# Output
# [25000 32000 45000 50000 62000 70000 92000 109250]

[ 25000.  32000.  45000.  50000.  62000.  70000.  92000. 109250.]


### OR OR OR, if you want keep the type as int only then

In [25]:
salary_copy = salary.copy()

salary_copy[salary_copy > 70000] = (salary_copy[salary_copy > 70000] * 1.15).astype(int)

print(salary_copy)

[ 25000  32000  45000  50000  62000  70000  92000 109249]


In [26]:
# ============================================================
# 18. FILTERING ROWS IN 2D ARRAYS
# ============================================================

# Select rows where first score > 50

rows = scores[scores[:,0] > 50]

print(rows)

# Output
# [[56 90 88]
#  [92 88 95]]

[[56 90 88]
 [92 88 95]]


In [27]:
# ============================================================
# 19. FILTERING COLUMNS
# ============================================================

# Select columns where average score > 70

column_means = scores.mean(axis=0)

print(column_means)

# Output
# [56.75 73.75 80.75]

[56.75 73.75 80.75]


In [28]:
selected_columns = scores[:, column_means > 70]

print(selected_columns)

# Output
# [[67 80]
#  [90 88]
#  [50 60]
#  [88 95]]


[[67 80]
 [90 88]
 [50 60]
 [88 95]]


In [29]:
# ============================================================
# 20. REPLACING VALUES USING BOOLEAN MASK
# ============================================================

ages_copy = ages.copy()

ages_copy[ages_copy > 40] = 100

print(ages_copy)

# Output
# [18. 22. 25. 30. 35. 40. 100. 100. nan]

[ 18.  22.  25.  30.  35.  40. 100. 100.  nan]


In [30]:
# ============================================================
# 21. REMOVE ELEMENTS BASED ON CONDITION
# ============================================================

filtered_salary = salary[salary >= 50000]

print(filtered_salary)

# Output
# [50000 62000 70000 80000 95000]

[50000 62000 70000 80000 95000]


In [31]:
# ============================================================
# 22. REPLACING NaN WITH np.nan_to_num()
# ============================================================

clean = np.nan_to_num(ages, nan=0)

print(clean)

# Output
# [18. 22. 25. 30. 35. 40. 45. 50. 0.]

[18. 22. 25. 30. 35. 40. 45. 50.  0.]
